export const JOB_ORDER_CATEGORIES = {
  "Cutting": [
    "Body Cutting",
    "Sleeve Cutting",
    "Collar Cutting",
    "Patti Cutting",
    "Rib Cutting",
    "Pocket Cutting",
    "Yoke Cutting",
    "Placket Cutting",
    "Panel Cutting",
    "Shoulder Tape Cutting",
    "Front & Back Panel Cutting",
    "Size Trimming",
    "Fusing Cutting (for collars/plackets)",
    "Other"
  ],
  "Stitching (Singer)": [
    "Patti Stitching",
    "Shoulder Join (Single Needle)",
    "Collar Attach (Top Stitch)",
    "Patti Box & Tack",
    "Placket Making",
    "Label Attachment (Back Neck)",
    "Sleeve Hem (Single Needle Hem)",
    "Bottom Hem (Single Needle Hem)",
    "Pocket Making",
    "Pocket Attachment",
    "Front Placket Top Stitch",
    "Back Neck Tape Attachment",
    "Side Slit Making",
    "Tack on Side Slit",
    "Button Stitching",
    "Buttonhole Making",
    "Collar Top Stitch",
    "Neck Tape Cover",
    "Shoulder Reinforcement Tape Stitch",
    "Bartack on Stress Points",
    "Peek (Neck/Shoulder/Sleeve)",
    "Other"
  ],
  "Stitching (Power Table) - Overlock": [
    "Shoulder Overlock",
    "Side Seam Overlock",
    "Sleeve Join Overlock",
    "Armhole Join Overlock",
    "Patti Clean Overlock",
    "Bottom Overlock (before hem)",
    "Rib/Cuff Overlock",
    "Collar Join Overlock",
    "Tape Overlock (inside neck)",
    "Side Slit Overlock",
    "Panel Attach Overlock",
    "Other"
  ],
  "Stitching (Power Table) - Flatlock": [
    "Shoulder Flatlock",
    "Side Seam Flatlock",
    "Armhole Flatlock",
    "Panel Flatlock",
    "Decorative Flatlock on Front",
    "Flatlock on Hem",
    "Flatlock on Sleeve Hem",
    "Back Yoke Flatlock",
    "Sports Seam Flatlock",
    "Other"
  ],
  "Checking": [
    "Thread Cutting",
    "Measurement Checking",
    "Shade Checking",
    "Stitch Quality Check",
    "Panel Matching Check",
    "Collar Shape Check",
    "Button & Buttonhole Check",
    "Label & Branding Check",
    "Fusing Strength Check",
    "Stains/Damages Check",
    "Final Quality Control (FQC)",
    "Other"
  ],
  "Ironing": [
    "Basic Ironing",
    "Collar Shape Ironing",
    "Patti Ironing",
    "Sleeve Ironing",
    "Body Ironing",
    "Flat Packing Ironing",
    "Crease Removing",
    "Steam Ironing",
    "Final Press",
    "Other"
  ],
  "Packing": [
    "Folding",
    "Tag Attachment",
    "Barcode Label Attachment",
    "Polybags Packing",
    "Size Sticker Placement",
    "Brand Sticker Placement",
    "Pairing & Set Creation",
    "Box Packing",
    "Final QA Before Packing",
    "Bundle Making",
    "Carton Sealing",
    "Carton Printing (optional)",
    "Other"
  ]
} as const;

export const OPERATIONS = [
  "Cutting",
  "Stitching (Singer)",
  "Stitching (Power Table) - Overlock",
  "Stitching (Power Table) - Flatlock",
  "Checking",
  "Ironing",
  "Packing",
];
