import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

export interface PurchaseOrder {
  id: string;
  po_number: string;
  purchase_date: string;
  supplier_id: string | null;
  category: string;
  payment_type: string;
  gst_type: string;
  invoice_number: string | null;
  invoice_date: string | null;
  subtotal: number;
  discount: number;
  cgst_rate: number;
  cgst_amount: number;
  sgst_rate: number;
  sgst_amount: number;
  igst_rate: number;
  igst_amount: number;
  grand_total: number;
  status: string;
  notes: string | null;
  locked_at: string | null;
  locked_by: string | null;
  created_at: string;
  updated_at: string;
  po_suppliers?: {
    id: string;
    supplier_name: string;
  } | null;
}

export interface POLineItem {
  id?: string;
  purchase_order_id?: string;
  item_name: string;
  quantity: number;
  unit: string;
  rate: number;
  amount: number;
}

export interface POFile {
  id: string;
  purchase_order_id: string;
  file_name: string;
  file_path: string;
  file_type: string | null;
  file_size: number | null;
  uploaded_at: string;
}

export interface POSupplier {
  id: string;
  supplier_name: string;
  contact_person: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  gst_number: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const usePurchaseOrders = () => {
  const queryClient = useQueryClient();

  const { data: purchaseOrders, isLoading, error } = useQuery({
    queryKey: ["purchase-orders"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("purchase_orders")
        .select(`
          *,
          po_suppliers (id, supplier_name)
        `)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as PurchaseOrder[];
    },
  });

  const { data: suppliers } = useQuery({
    queryKey: ["po-suppliers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("po_suppliers")
        .select("*")
        .eq("is_active", true)
        .order("supplier_name");
      
      if (error) throw error;
      return data as POSupplier[];
    },
  });

  const createPurchaseOrder = useMutation({
    mutationFn: async (data: {
      purchase: Omit<PurchaseOrder, "id" | "po_number" | "created_at" | "updated_at" | "po_suppliers">;
      lineItems: POLineItem[];
    }) => {
      // Create purchase order - po_number auto-generated by database trigger
      const { data: po, error: poError } = await supabase
        .from("purchase_orders")
        .insert([{ ...data.purchase, po_number: '' }])
        .select()
        .single();
      
      if (poError) throw poError;

      // Create line items
      if (data.lineItems.length > 0) {
        const lineItemsWithPOId = data.lineItems.map(item => ({
          item_name: item.item_name,
          quantity: item.quantity,
          unit: item.unit,
          rate: item.rate,
          amount: item.amount,
          purchase_order_id: po.id,
        }));
        
        const { error: lineItemsError } = await supabase
          .from("po_line_items")
          .insert(lineItemsWithPOId);
        
        if (lineItemsError) throw lineItemsError;
      }

      return po;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
      toast({ title: "Purchase order created successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error creating purchase order", description: error.message, variant: "destructive" });
    },
  });

  const updatePurchaseOrder = useMutation({
    mutationFn: async (data: {
      id: string;
      purchase: Partial<PurchaseOrder>;
      lineItems?: POLineItem[];
    }) => {
      const { error: poError } = await supabase
        .from("purchase_orders")
        .update(data.purchase)
        .eq("id", data.id);
      
      if (poError) throw poError;

      if (data.lineItems) {
        // Delete existing line items and re-insert
        await supabase
          .from("po_line_items")
          .delete()
          .eq("purchase_order_id", data.id);
        
        if (data.lineItems.length > 0) {
          const lineItemsWithPOId = data.lineItems.map(item => ({
            ...item,
            purchase_order_id: data.id,
          }));
          
          const { error: lineItemsError } = await supabase
            .from("po_line_items")
            .insert(lineItemsWithPOId);
          
          if (lineItemsError) throw lineItemsError;
        }
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
      toast({ title: "Purchase order updated successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error updating purchase order", description: error.message, variant: "destructive" });
    },
  });

  const lockPurchaseOrder = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("purchase_orders")
        .update({ 
          status: "locked", 
          locked_at: new Date().toISOString(),
        })
        .eq("id", id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
      toast({ title: "Purchase order locked successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error locking purchase order", description: error.message, variant: "destructive" });
    },
  });

  const deletePurchaseOrder = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("purchase_orders")
        .delete()
        .eq("id", id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
      toast({ title: "Purchase order deleted successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error deleting purchase order", description: error.message, variant: "destructive" });
    },
  });

  const createSupplier = useMutation({
    mutationFn: async (data: Omit<POSupplier, "id" | "created_at" | "updated_at">) => {
      const { data: supplier, error } = await supabase
        .from("po_suppliers")
        .insert(data)
        .select()
        .single();
      
      if (error) throw error;
      return supplier;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["po-suppliers"] });
      toast({ title: "Supplier added successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error adding supplier", description: error.message, variant: "destructive" });
    },
  });

  const getLineItems = async (purchaseOrderId: string) => {
    const { data, error } = await supabase
      .from("po_line_items")
      .select("*")
      .eq("purchase_order_id", purchaseOrderId);
    
    if (error) throw error;
    return data as POLineItem[];
  };

  const getFiles = async (purchaseOrderId: string) => {
    const { data, error } = await supabase
      .from("po_files")
      .select("*")
      .eq("purchase_order_id", purchaseOrderId);
    
    if (error) throw error;
    return data as POFile[];
  };

  const uploadFile = async (purchaseOrderId: string, file: File) => {
    const year = new Date().getFullYear();
    const { data: po } = await supabase
      .from("purchase_orders")
      .select("po_number")
      .eq("id", purchaseOrderId)
      .single();
    
    const filePath = `${year}/${po?.po_number}/${Date.now()}_${file.name}`;
    
    const { error: uploadError } = await supabase.storage
      .from("purchase-bills")
      .upload(filePath, file);
    
    if (uploadError) throw uploadError;

    const { error: dbError } = await supabase
      .from("po_files")
      .insert({
        purchase_order_id: purchaseOrderId,
        file_name: file.name,
        file_path: filePath,
        file_type: file.type,
        file_size: file.size,
      });
    
    if (dbError) throw dbError;
    
    queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
    return filePath;
  };

  const deleteFile = async (fileId: string, filePath: string) => {
    await supabase.storage
      .from("purchase-bills")
      .remove([filePath]);
    
    const { error } = await supabase
      .from("po_files")
      .delete()
      .eq("id", fileId);
    
    if (error) throw error;
    queryClient.invalidateQueries({ queryKey: ["purchase-orders"] });
  };

  return {
    purchaseOrders,
    suppliers,
    isLoading,
    error,
    createPurchaseOrder,
    updatePurchaseOrder,
    lockPurchaseOrder,
    deletePurchaseOrder,
    createSupplier,
    getLineItems,
    getFiles,
    uploadFile,
    deleteFile,
  };
};
