import { useRef } from 'react';
import { ArrowLeft, Download, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { format } from 'date-fns';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import type { EwayBill } from '@/hooks/useDCDocuments';

interface Props {
  bill: EwayBill;
  onBack: () => void;
}

export default function EwayBillPreview({ bill, onBack }: Props) {
  const printRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!printRef.current) return;
    const canvas = await html2canvas(printRef.current, { scale: 2, useCORS: true });
    const imgData = canvas.toDataURL('image/jpeg', 0.85);
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`E-Way-Bill_${bill.eway_bill_no || 'draft'}.pdf`);
  };

  const handlePrint = () => window.print();

  const fmtDate = (d: string | null) => {
    if (!d) return '';
    try { return format(new Date(d), 'dd-MMM-yy'); } catch { return d; }
  };

  const fmtDateTime = (d: string | null) => {
    if (!d) return '';
    try { return format(new Date(d), 'dd-MMM-yy hh:mm a'); } catch { return d; }
  };

  const fmtCurrency = (n: number) => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between print:hidden">
        <Button variant="ghost" onClick={onBack}><ArrowLeft className="h-4 w-4 mr-2" />Back to Edit</Button>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handlePrint}><Printer className="h-4 w-4 mr-1" />Print</Button>
          <Button onClick={handleDownload}><Download className="h-4 w-4 mr-1" />Download PDF</Button>
        </div>
      </div>

      <div className="flex justify-center">
        <div
          ref={printRef}
          className="bg-white text-black shadow-lg"
          style={{
            width: '210mm',
            minHeight: '297mm',
            padding: '15mm 18mm',
            fontFamily: "'Inter', Arial, sans-serif",
            fontSize: '11px',
            lineHeight: '1.4',
          }}
        >
          {/* Title */}
          <div className="text-center mb-4">
            <h1 className="text-lg font-bold border-b-2 border-black pb-1 inline-block">e-Way Bill</h1>
          </div>

          {/* Tax Invoice & IRN block */}
          {(bill.tax_invoice_no || bill.irn) && (
            <div className="mb-4 text-[10px] border border-gray-300 p-2 rounded">
              {bill.tax_invoice_no && <p><strong>Tax Invoice</strong> - {bill.tax_invoice_no} | {fmtDate(bill.tax_invoice_date as string)}</p>}
              {bill.irn && <p><strong>IRN</strong>: {bill.irn}</p>}
              {bill.ack_no && <p><strong>Ack No</strong>: {bill.ack_no} | <strong>Ack Date</strong>: {fmtDate(bill.ack_date as string)}</p>}
            </div>
          )}

          {/* Section 1 */}
          <div className="border border-gray-400 mb-3">
            <div className="bg-gray-100 px-3 py-1 font-bold text-xs border-b border-gray-400">1. e-Way Bill Details</div>
            <div className="grid grid-cols-3 gap-0 text-[10px]">
              <Cell label="e-Way Bill No." value={bill.eway_bill_no} />
              <Cell label="Mode" value={bill.mode} />
              <Cell label="Generated Date" value={fmtDateTime(bill.eway_bill_date)} />
              <Cell label="Generated By" value={bill.generated_by_gstin} />
              <Cell label="Approx Distance" value={bill.approx_distance ? `${bill.approx_distance} KM` : ''} />
              <Cell label="Valid Upto" value={fmtDateTime(bill.valid_upto)} />
              <Cell label="Supply Type" value={bill.supply_type} />
              <Cell label="Transaction Type" value={bill.transaction_type} />
              <Cell label="" value="" />
            </div>
          </div>

          {/* Section 2 */}
          <div className="border border-gray-400 mb-3">
            <div className="bg-gray-100 px-3 py-1 font-bold text-xs border-b border-gray-400">2. Address Details</div>
            <div className="grid grid-cols-2 gap-0">
              <div className="border-r border-gray-400 p-2 text-[10px]">
                <p className="font-bold mb-1">From</p>
                <p className="font-semibold">{bill.from_name}</p>
                <p>GSTIN: {bill.from_gstin}</p>
                <p>{bill.from_state}</p>
                <p className="mt-1 font-bold text-[9px]">Dispatch From</p>
                <p>{bill.dispatch_from}</p>
              </div>
              <div className="p-2 text-[10px]">
                <p className="font-bold mb-1">To</p>
                <p className="font-semibold">{bill.to_name}</p>
                <p>GSTIN: {bill.to_gstin}</p>
                <p>{bill.to_state}</p>
                <p className="mt-1 font-bold text-[9px]">Ship To</p>
                <p>{bill.ship_to}</p>
              </div>
            </div>
          </div>

          {/* Section 3 - Goods */}
          <div className="border border-gray-400 mb-3">
            <div className="bg-gray-100 px-3 py-1 font-bold text-xs border-b border-gray-400">3. Goods Details</div>
            <table className="w-full text-[10px]" style={{ borderCollapse: 'collapse' }}>
              <thead>
                <tr className="border-b border-gray-400">
                  <th className="border-r border-gray-400 p-1 text-left">HSN Code</th>
                  <th className="border-r border-gray-400 p-1 text-left">Product Name & Desc</th>
                  <th className="border-r border-gray-400 p-1 text-right">Quantity</th>
                  <th className="border-r border-gray-400 p-1 text-right">Taxable Amt</th>
                  <th className="p-1 text-center">Tax Rate (C+S)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border-r border-gray-400 p-1">{bill.hsn_code}</td>
                  <td className="border-r border-gray-400 p-1">{bill.product_description}</td>
                  <td className="border-r border-gray-400 p-1 text-right">{bill.quantity} {bill.uom}</td>
                  <td className="border-r border-gray-400 p-1 text-right">{fmtCurrency(bill.taxable_amount || 0)}</td>
                  <td className="p-1 text-center">{bill.tax_rate_cgst}+{bill.tax_rate_sgst}</td>
                </tr>
              </tbody>
            </table>
            {/* Tax summary */}
            <div className="border-t border-gray-400 p-2 text-[10px] grid grid-cols-4 gap-2">
              <div><strong>Tot. Taxable Amt:</strong> {fmtCurrency(bill.taxable_amount || 0)}</div>
              <div><strong>CGST Amt:</strong> {fmtCurrency(bill.cgst_amount || 0)}</div>
              <div><strong>SGST Amt:</strong> {fmtCurrency(bill.sgst_amount || 0)}</div>
              <div><strong>Total Inv Amt:</strong> <span className="font-bold">{fmtCurrency(bill.total_invoice_amount || 0)}</span></div>
            </div>
            {bill.other_amount !== 0 && (
              <div className="border-t border-gray-400 px-2 py-1 text-[10px]"><strong>Other Amt:</strong> {fmtCurrency(bill.other_amount || 0)}</div>
            )}
          </div>

          {/* Section 4 */}
          <div className="border border-gray-400 mb-3">
            <div className="bg-gray-100 px-3 py-1 font-bold text-xs border-b border-gray-400">4. Transportation Details</div>
            <div className="grid grid-cols-2 gap-0 text-[10px]">
              <Cell label="Transporter ID" value={bill.transporter_id} />
              <Cell label="Doc No." value={bill.doc_no} />
              <Cell label="Name" value={bill.transporter_name} />
              <Cell label="Date" value={fmtDate(bill.doc_date as string)} />
            </div>
          </div>

          {/* Section 5 */}
          <div className="border border-gray-400">
            <div className="bg-gray-100 px-3 py-1 font-bold text-xs border-b border-gray-400">5. Vehicle Details</div>
            <div className="grid grid-cols-3 gap-0 text-[10px]">
              <Cell label="Vehicle No." value={bill.vehicle_no} />
              <Cell label="From" value={bill.vehicle_from} />
              <Cell label="CEWB No." value={bill.cewb_no} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Cell({ label, value }: { label: string; value: string | null | undefined }) {
  return (
    <div className="border-b border-r border-gray-300 px-2 py-1">
      {label && <span className="font-semibold">{label}: </span>}
      <span>{value || ''}</span>
    </div>
  );
}
